# Generated by Django 2.2.6 on 2019-10-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Cliente'),
            preserve_default=False,
        ),
    ]
