# Generated by Django 2.2.6 on 2019-10-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0002_mensajes_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='cliente',
            new_name='clientees',
        ),
    ]
