# Generated by Django 2.2.6 on 2019-10-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0003_auto_20191020_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=35)),
                ('Password', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarioes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajes',
            name='tmensajees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Tipo_Mensaje'),
            preserve_default=False,
        ),
    ]
