# Generated by Django 2.2.6 on 2019-10-20 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0006_auto_20191020_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuarioes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Usuario', unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='User',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
