# Generated by Django 2.2.6 on 2019-10-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0007_auto_20191020_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Elo_Usuario', models.CharField(max_length=40, unique=True)),
                ('Puntaje_minimo', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomRegion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timagen', models.CharField(max_length=35, unique=True)),
            ],
        ),
    ]
