# Generated by Django 2.2.6 on 2019-10-20 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0008_nivel_usuario_region_tipo_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Imagen',
            new_name='Tipo_img',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Ciudad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Regiones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galeria',
            name='TPimagen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Tipo_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Nivel_Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Puntaje',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
