# Generated by Django 2.2.6 on 2019-10-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0009_auto_20191020_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Galeria'),
        ),
    ]
