# Generated by Django 2.2.6 on 2019-10-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0010_auto_20191020_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='mensajes',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='nivel_usuario',
            options={'verbose_name': 'Nivel de Usuario', 'verbose_name_plural': 'Nivel de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='tipo_img',
            options={'verbose_name': 'Tipo de Imagen', 'verbose_name_plural': 'Tipo de Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='tipo_mensaje',
            options={'verbose_name': 'Tipo de mensaje', 'verbose_name_plural': 'Tipos de mensajes'},
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='Mensaje',
            field=models.CharField(max_length=500),
        ),
    ]
