# Generated by Django 2.2.6 on 2019-10-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0011_auto_20191025_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='Mensaje',
            field=models.CharField(max_length=2500),
        ),
    ]
