# Generated by Django 2.2.6 on 2019-10-25 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0015_auto_20191025_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Admin_Pagina'),
        ),
    ]
