# Generated by Django 2.2.6 on 2019-10-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0016_auto_20191025_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Noticias'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Link_YT',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
