# Generated by Django 2.2.6 on 2019-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0017_auto_20191025_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='clientees',
            field=models.CharField(max_length=150),
        ),
    ]
