# Generated by Django 2.2.6 on 2019-10-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0018_auto_20191025_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='RegionMensaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajes',
            name='Telefonomensaje',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensajes',
            name='emailmensaje',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
