# Generated by Django 2.2.6 on 2019-11-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0019_auto_20191025_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuarioes',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Nivel_Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='Password',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='Puntaje',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='User',
            field=models.CharField(default=1, max_length=35, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentarios_noti',
            name='Usuariocom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_WOP.Cliente'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
