# Generated by Django 2.2.6 on 2019-11-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0021_auto_20191103_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Password',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='User',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
