# Generated by Django 2.2.6 on 2019-11-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0023_auto_20191103_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Email',
        ),
    ]
