# Generated by Django 2.2.6 on 2019-11-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0024_remove_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Nombre',
        ),
    ]
