# Generated by Django 2.2.6 on 2019-11-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0025_remove_cliente_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('AdminGen', 'Es administrador General'), ('AdminPag', 'Es administrador de la pagina'))},
        ),
    ]
