# Generated by Django 2.2.6 on 2019-11-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_WOP', '0026_auto_20191115_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Autor',
            field=models.CharField(max_length=50),
        ),
    ]
